### ISSUE TITLE
def'd square function fails

### ISSUE THREAD

**Issue by JulianLeviston** [Raynes/tryclojure#51]
Browser is Safari Version 8.0.2 (10600.2.5) Mac OS/X Yosemite 10.10.1

    > (def square (fn [x] (* x x)))
    #'sandbox32479/square
    > (square 10)
    java.lang.IllegalStateException: Attempting to call unbound fn: #'sandbox32479/square

**Comment by switchhax** [comment]
Please, if possible, try another browser, just for fun. (Maybe try the anonymous function.)

**Comment by JulianLeviston** [comment]
Trying a different browser won't fix this problem.

This is an error report... I recommended try clojure to a friend, and ran through to make sure it was all about the right level for her, and encountered that error.

**Comment by switchhax** [comment]
But it would solve the need to ... for a while. (Well in school it worked perfectly for me...)

**Comment by Raynes** [comment]
It works for me. I'm not sure what to say. The sandbox must have, for some reason, wiped your defs right after you made that. Is this a persistent issue or a one-time thing?

**Comment by JulianLeviston** [comment]
Apologies, all. I tried today and it worked just fine. Must have been a temporary aberration.

**Comment by DavidRagone** [comment]
I just ran into this as well :/ Not sure what meaningful info I can contribute. It worked if I opened it up in chrome incognito, but continued to fail if I just reloaded the page.

**Comment by recarreira** [comment]
Had the same problem here, also worked with chrome incognito.

**Comment by joymon** [comment]
Same here. Worked in Chrome incognito. Is it storing any state in browser?

**Comment by joymon** [comment]
Cleared cookies in Chrome and it worked.No need of incognito mode.

**Comment by 3rojka** [comment]
clearing cookies helped
