### ISSUE TITLE
Tutorial, define fn without defn - Unable to resolve symbol: x

### ISSUE THREAD

**Issue by SpikesDivZero** [Raynes/tryclojure#52]
Proceeding through the tutorial results in the following error:

    > (def square (fn [x] (* x x)))
    java.lang.RuntimeException: Unable to resolve symbol: x in this context

On the step:

    If you want, you can create a named functions without using defn: type

**Comment by Raynes** [comment]
Works for me. Probably a transient issue. Can you try again in a different browser or something?

**Comment by SpikesDivZero** [comment]
Works in a new In Private browsing session, but still is broken in the other window. Dumped cookies to file in the (albeit unlikely) event that you're interested in debugging, but otherwise, this can be closed. :)

Sorry for the bad bug report -- I failed to do my due diligence here. :)

**Comment by Raynes** [comment]
:( I care!

I haven't been doing much with this because I would really rather rewrite it without clojail giving folks their own personal jvms! It's just that that requires having a lot of machines for JVMs which I do not have at the moment.

**Comment by SpikesDivZero** [comment]
Apologies, I certainly didn't mean to suggest that you did not care. I just know from personal experience that in the greater scope of things (life, work, hobbies, family, etc) debugging a one-off issue that others have not experienced usually doesn't rank too highly in priority, personally. Nothing negative was indented, and again, apologies. :)

**Comment by Raynes** [comment]
Yer the kinda dude I like to hang out with.

Thanks and no apologies necessary, sir.
