### ISSUE TITLE
Problem with tryclj.com

### ISSUE THREAD

**Issue by MaxJust** [Raynes/tryclojure#55]
Hi, I have a problem with examples on tryclj.com. Here my output:
```
> (defn square [x] (* x x))
#'sandbox6120/square
> (square 10)
java.lang.IllegalStateException: Attempting to call unbound fn: #'sandbox6120/square
```

**Comment by Frozenlock** [comment]
Same here:

```clj

> (defn square [x] (* x x))
#'sandbox9943/square
> (square 10)
java.lang.IllegalStateException: Attempting to call unbound fn: #'sandbox9943/square

```

**Comment by eprogramming** [comment]
same here
![a](https://cloud.githubusercontent.com/assets/6443576/7264914/40da0756-e868-11e4-9659-f5eb880ec00b.png)

**Comment by Raynes** [comment]
There are several tickets regarding this. I do not intend to fix these issues any time soon. I simply don't have time to do what needs to be done.
